# Generated by Django 5.1 on 2024-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biharjobs',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
