# Generated by Django 5.1 on 2024-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_biharjobs_title_alter_bngjobs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biharjobs',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='biharjobs',
            name='company',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='biharjobs',
            name='eligibility',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='biharjobs',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
